// server/staticData.js

// =======================
// 📌 STATIC USER LIST FOR UI TESTING
// (Remove after API integration)
// =======================
export const dummyUsers = [
    {
        _id: "1",
        userId: "user001",
        fullName: "Amit Sharma",
        email: "amit.sharma@example.com",
        avatar: "https://i.pravatar.cc/150?img=1",
        lastLogin: "2025-01-10T10:32:00Z",
        role: "SUPER_ADMIN",
        status: "ACTIVE",
        userStatus: "APPROVED",
    },
    {
        _id: "2",
        userId: "user002",
        fullName: "Priya Sen",
        email: "priya.sen@example.com",
        avatar: "https://i.pravatar.cc/150?img=2",
        lastLogin: "2025-01-09T09:10:00Z",
        role: "ENGINEER",
        status: "ACTIVE",
        userStatus: "PENDING",
    },
    {
        _id: "3",
        userId: "user003",
        fullName: "Rohit Verma",
        email: "rohit.verma@example.com",
        avatar: "https://i.pravatar.cc/150?img=3",
        lastLogin: "2025-01-08T08:22:00Z",
        role: "ENGINEER",
        status: "INACTIVE",
        userStatus: "APPROVED",
    },
    {
        _id: "4",
        userId: "user004",
        fullName: "Sneha Gupta",
        email: "sneha.gupta@example.com",
        avatar: "https://i.pravatar.cc/150?img=4",
        lastLogin: "2025-01-11T13:14:00Z",
        role: "ENGINEER",
        status: "ACTIVE",
        userStatus: "PENDING",
    },
    {
        _id: "5",
        userId: "user005",
        fullName: "Vikram Kumar",
        email: "vikram.kumar@example.com",
        avatar: "https://i.pravatar.cc/150?img=5",
        lastLogin: "2025-01-07T17:48:00Z",
        role: "SUPER_ADMIN",
        status: "ACTIVE",
        userStatus: "APPROVED",
    },
    {
        _id: "6",
        userId: "user006",
        fullName: "Anjali Mishra",
        email: "anjali.mishra@example.com",
        avatar: "https://i.pravatar.cc/150?img=6",
        lastLogin: "2025-01-05T14:20:00Z",
        role: "ENGINEER",
        status: "INACTIVE",
        userStatus: "APPROVED",
    },
    {
        _id: "7",
        userId: "user007",
        fullName: "Karan Singh",
        email: "karan.singh@example.com",
        avatar: "https://i.pravatar.cc/150?img=7",
        lastLogin: "2025-01-03T11:45:00Z",
        role: "ENGINEER",
        status: "ACTIVE",
        userStatus: "PENDING",
    },
    {
        _id: "8",
        userId: "user008",
        fullName: "Neha Patel",
        email: "neha.patel@example.com",
        avatar: "https://i.pravatar.cc/150?img=8",
        lastLogin: "2025-01-04T10:55:00Z",
        role: "ENGINEER",
        status: "ACTIVE",
        userStatus: "APPROVED",
    },
    {
        _id: "9",
        userId: "user009",
        fullName: "Rahul Das",
        email: "rahul.das@example.com",
        avatar: "https://i.pravatar.cc/150?img=9",
        lastLogin: "2025-01-02T12:12:00Z",
        role: "ENGINEER",
        status: "INACTIVE",
        userStatus: "PENDING",
    },
    {
        _id: "10",
        userId: "user010",
        fullName: "Divya Reddy",
        email: "divya.reddy@example.com",
        avatar: "https://i.pravatar.cc/150?img=10",
        lastLogin: "2025-01-01T09:00:00Z",
        role: "ENGINEER",
        status: "ACTIVE",
        userStatus: "APPROVED",
    },

    // Remaining 10 users
    {
        _id: "11",
        userId: "user011",
        fullName: "Arjun Roy",
        email: "arjun.roy@example.com",
        avatar: "https://i.pravatar.cc/150?img=11",
        lastLogin: "2024-12-30T14:00:00Z",
        role: "ENGINEER",
        status: "ACTIVE",
        userStatus: "PENDING",
    },
    {
        _id: "12",
        userId: "user012",
        fullName: "Meera Nair",
        email: "meera.nair@example.com",
        avatar: "https://i.pravatar.cc/150?img=12",
        lastLogin: "2024-12-29T15:15:00Z",
        role: "SUPER_ADMIN",
        status: "ACTIVE",
        userStatus: "APPROVED",
    },
    {
        _id: "13",
        userId: "user013",
        fullName: "Saurav Jain",
        email: "saurav.jain@example.com",
        avatar: "https://i.pravatar.cc/150?img=13",
        lastLogin: "2024-12-28T18:10:00Z",
        role: "ENGINEER",
        status: "INACTIVE",
        userStatus: "PENDING",
    },
    {
        _id: "14",
        userId: "user014",
        fullName: "Tanya Kapoor",
        email: "tanya.kapoor@example.com",
        avatar: "https://i.pravatar.cc/150?img=14",
        lastLogin: "2024-12-27T13:05:00Z",
        role: "ENGINEER",
        status: "ACTIVE",
        userStatus: "APPROVED",
    },
    {
        _id: "15",
        userId: "user015",
        fullName: "Harshit Mehta",
        email: "harshit.mehta@example.com",
        avatar: "https://i.pravatar.cc/150?img=15",
        lastLogin: "2024-12-26T16:20:00Z",
        role: "ENGINEER",
        status: "ACTIVE",
        userStatus: "PENDING",
    },
    {
        _id: "16",
        userId: "user016",
        fullName: "Shreya Kulkarni",
        email: "shreya.kulkarni@example.com",
        avatar: "https://i.pravatar.cc/150?img=16",
        lastLogin: "2024-12-25T11:12:00Z",
        role: "ENGINEER",
        status: "INACTIVE",
        userStatus: "APPROVED",
    },
    {
        _id: "17",
        userId: "user017",
        fullName: "Aakash Malhotra",
        email: "aakash.malhotra@example.com",
        avatar: "https://i.pravatar.cc/150?img=17",
        lastLogin: "2024-12-24T10:30:00Z",
        role: "SUPER_ADMIN",
        status: "ACTIVE",
        userStatus: "PENDING",
    },
    {
        _id: "18",
        userId: "user018",
        fullName: "Ishita Bose",
        email: "ishita.bose@example.com",
        avatar: "https://i.pravatar.cc/150?img=18",
        lastLogin: "2024-12-23T09:00:00Z",
        role: "ENGINEER",
        status: "ACTIVE",
        userStatus: "APPROVED",
    },
    {
        _id: "19",
        userId: "user019",
        fullName: "Rajan Khanna",
        email: "rajan.khanna@example.com",
        avatar: "https://i.pravatar.cc/150?img=19",
        lastLogin: "2024-12-22T12:10:00Z",
        role: "ENGINEER",
        status: "INACTIVE",
        userStatus: "PENDING",
    },
    {
        _id: "20",
        userId: "user020",
        fullName: "Pooja Malviya",
        email: "pooja.malviya@example.com",
        avatar: "https://i.pravatar.cc/150?img=20",
        lastLogin: "2024-12-21T15:45:00Z",
        role: "ENGINEER",
        status: "ACTIVE",
        userStatus: "APPROVED",
    },
];
